# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# ---------------------------------------------------------
"""Scenario: Datastore registration & round-trip across credential shapes.

Mirrors the customer pattern from:
  https://github.com/Azure/azureml-examples/tree/main/sdk/python/resources/datastores

Customer story:
  A data engineer registers external storage (Azure Blob, ADLS Gen2) as datastores so jobs can read
  and write data by reference. Datastore creation serializes the entity to the wire; a mixed
  entity/operation client once produced ``TypeError: Object of type Datastore is not JSON
  serializable`` when the entity and the operation client disagreed on model flavour.

  This exercises datastore entity serialization (arm ``Datastore`` + credential models) regenerated by
  the TypeSpec migration. It is a regression guard for that serialization class: a broken wire raises
  ``TypeError`` *before* the request is sent, so the test fails on ``TypeError`` and skips on ordinary
  service-side validation errors.

Steps:
  1. Register an identity-based Azure Blob datastore; assert no serialization TypeError; round-trip
  2. Register an identity-based ADLS Gen2 datastore; assert no serialization TypeError; round-trip
  3. List datastores and verify both appear
  4. Clean up (delete both datastores)
"""

import pytest

from azure.ai.ml import MLClient
from azure.ai.ml.entities import AzureBlobDatastore, AzureDataLakeGen2Datastore
from azure.core.exceptions import HttpResponseError


class TestScenarioDatastoreCredentials:
    """Datastore registration and round-trip fidelity (serialization regression guard)."""

    @pytest.mark.timeout(600)
    def test_blob_and_adls_datastore_round_trip(self, ml_client: MLClient, rand_name):
        """Register identity-based blob + ADLS Gen2 datastores and verify faithful round-trips."""
        blob_name = rand_name("blobds").replace("-", "_")
        adls_name = rand_name("adlsds").replace("-", "_")
        created_names = []
        try:
            # ── Step 1: identity-based Azure Blob datastore ───────
            blob_ds = AzureBlobDatastore(
                name=blob_name,
                description="scenario blob datastore (identity-based)",
                account_name="scenariostorageacct",
                container_name="scenario-container",
                tags={"scenario": "datastore", "auth": "identity"},
            )
            try:
                created_blob = ml_client.datastores.create_or_update(blob_ds)
            except TypeError as ex:  # the original mixed-tree serialization regression
                pytest.fail(f"blob datastore serialization regression: {ex}")
            except HttpResponseError as ex:
                pytest.skip(f"blob datastore create failed for a service reason (not serialization): {ex}")
            created_names.append(blob_name)
            assert created_blob.name == blob_name

            fetched_blob = ml_client.datastores.get(blob_name)
            assert fetched_blob.name == blob_name
            assert fetched_blob.account_name == "scenariostorageacct"
            assert fetched_blob.container_name == "scenario-container"
            assert fetched_blob.tags.get("auth") == "identity"

            # ── Step 2: identity-based ADLS Gen2 datastore ────────
            adls_ds = AzureDataLakeGen2Datastore(
                name=adls_name,
                description="scenario ADLS Gen2 datastore (identity-based)",
                account_name="scenariodatalake",
                filesystem="scenario-fs",
                tags={"scenario": "datastore", "auth": "identity", "kind": "adls_gen2"},
            )
            try:
                created_adls = ml_client.datastores.create_or_update(adls_ds)
            except TypeError as ex:
                pytest.fail(f"ADLS Gen2 datastore serialization regression: {ex}")
            except HttpResponseError as ex:
                pytest.skip(f"ADLS Gen2 datastore create failed for a service reason (not serialization): {ex}")
            created_names.append(adls_name)
            assert created_adls.name == adls_name

            fetched_adls = ml_client.datastores.get(adls_name)
            assert fetched_adls.account_name == "scenariodatalake"
            assert fetched_adls.filesystem == "scenario-fs"

            # ── Step 3: both appear in the listing ────────────────
            listed = {ds.name for ds in ml_client.datastores.list()}
            assert blob_name in listed
            assert adls_name in listed
        finally:
            # ── Step 4: cleanup ──
            for name in created_names:
                try:
                    ml_client.datastores.delete(name)
                except Exception as ex:  # pragma: no cover - best-effort cleanup
                    print(f"cleanup: could not delete datastore {name} — {ex}")
