# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# ---------------------------------------------------------
"""Scenario: Custom-container online deployment — inference_config routes accepted end-to-end.

Mirrors the customer pattern from:
  https://github.com/Azure/azureml-examples/tree/main/sdk/python/endpoints/online/custom-container
  (online-endpoints-custom-container.ipynb)

Customer story:
  An ML engineer serves a model with a custom web server (TF Serving) behind a managed online
  endpoint. The Environment declares ``inference_config`` with liveness/readiness/scoring routes so
  Azure ML can health-check and route scoring traffic to the container. When the deployment is
  submitted, the service validates that all three routes are present with the correct camelCase wire
  keys — if any is dropped or mis-cased it rejects with "You must specify all three of: liveness,
  readiness and scoring routes".

  This reproduces the exact failing sample end-to-end at the *deployment* level and is a regression
  guard for the ``inference_config`` serialization path (arm ``InferenceContainerProperties`` /
  ``Route``) regenerated by the TypeSpec migration. The test asserts the deployment submission is NOT
  rejected for a route reason; it does not wait for full container provisioning (which needs a real
  servable model) and skips gracefully on unrelated infra errors (quota, image pull, model health).

Steps:
  1. Create a managed online endpoint
  2. Submit a custom-container deployment whose Environment carries inference_config (raw dict, as the
     sample notebook does)
  3. Assert the submission is accepted (routes validated) — fail only if the service rejects the
     three-routes contract
  4. Clean up (delete the endpoint, which cancels any in-flight provisioning)
"""

import os
import tempfile

import pytest

from azure.ai.ml import MLClient
from azure.ai.ml.entities import Environment, ManagedOnlineDeployment, ManagedOnlineEndpoint, Model
from azure.core.exceptions import HttpResponseError

_ROUTES_ERROR_MARKER = "liveness, readiness and scoring routes"


def _fail_if_routes_rejected(ex: Exception):
    """Fail the test only if the service rejected the inference_config three-routes contract."""
    msg = str(ex).lower()
    if _ROUTES_ERROR_MARKER in msg or ("liveness" in msg and "readiness" in msg and "scoring" in msg):
        pytest.fail(f"inference_config routes rejected by service — TSP wire regression: {ex}")


class TestScenarioCustomContainerEndpoint:
    """Custom-container deployment: inference_config routes must be accepted at deployment submission."""

    @pytest.mark.timeout(1800)
    def test_custom_container_inference_config_accepted(self, ml_client: MLClient, rand_name):
        """Submit a custom-container deployment and assert its inference_config routes are accepted."""
        endpoint_name = rand_name("ccep")[:32]
        model_name = rand_name("ccmdl")
        try:
            # ── Step 1: create the endpoint ───────────────────────
            endpoint = ManagedOnlineEndpoint(
                name=endpoint_name,
                description="Scenario: custom-container inference_config route validation",
                auth_mode="key",
                tags={"scenario": "custom-container", "branch": "tsp-migration"},
            )
            ml_client.online_endpoints.begin_create_or_update(endpoint).result()

            with tempfile.TemporaryDirectory() as tmpdir:
                # Minimal placeholder model dir (the container mounts its own model; the wire path is
                # what we validate, not the served model itself).
                model_dir = os.path.join(tmpdir, "model")
                os.makedirs(model_dir, exist_ok=True)
                with open(os.path.join(model_dir, "model.txt"), "w", encoding="utf-8") as f:
                    f.write("placeholder model for custom-container scenario")

                # ── Step 2: custom-container Environment with inference_config (raw dict, sample style) ──
                env = Environment(
                    image="docker.io/tensorflow/serving:latest",
                    inference_config={
                        "liveness_route": {"port": 8501, "path": "/v1/models/half_plus_two"},
                        "readiness_route": {"port": 8501, "path": "/v1/models/half_plus_two"},
                        "scoring_route": {"port": 8501, "path": "/v1/models/half_plus_two:predict"},
                    },
                )
                deployment = ManagedOnlineDeployment(
                    name="blue",
                    endpoint_name=endpoint_name,
                    model=Model(name=model_name, version="1", path=model_dir),
                    environment=env,
                    environment_variables={
                        "MODEL_BASE_PATH": "/var/azureml-app/azureml-models/model/1",
                        "MODEL_NAME": "half_plus_two",
                    },
                    instance_type="Standard_DS3_v2",
                    instance_count=1,
                )

                # ── Step 3: submit; the service validates the three routes synchronously ──
                try:
                    poller = ml_client.online_deployments.begin_create_or_update(deployment)
                except HttpResponseError as ex:
                    _fail_if_routes_rejected(ex)
                    pytest.skip(f"deployment submission failed for a non-route reason (infra/quota/model): {ex}")
                else:
                    # Submission accepted => the inference_config routes serialized correctly.
                    # Do not wait for full provisioning (placeholder model won't become healthy); if the
                    # poller surfaces an early error, still fail only on the route contract.
                    assert poller is not None
                    try:
                        poller.result(timeout=120)
                    except HttpResponseError as ex:
                        _fail_if_routes_rejected(ex)
                    except Exception as ex:  # noqa: BLE001 - provisioning timeout/health is not our concern
                        _fail_if_routes_rejected(ex)
        finally:
            # ── Step 4: cleanup (cancels in-flight provisioning) ──
            try:
                ml_client.online_endpoints.begin_delete(name=endpoint_name)
            except Exception as ex:  # pragma: no cover - best-effort cleanup
                print(f"cleanup: could not delete endpoint {endpoint_name} — {ex}")
