# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# ---------------------------------------------------------
"""Scenario: Registry asset lifecycle — environment, data, and model create + round-trip.

Mirrors the customer pattern from:
  https://github.com/Azure/azureml-examples/tree/main/sdk/python/assets/assets-in-registry
  (share-data-using-registry.ipynb, share-models-components-environments.ipynb)

Customer story:
  A platform team publishes shared environments, data assets, and models to an organization-wide
  Registry so downstream workspaces can consume them. Registry asset creation goes through the
  data-plane registry endpoint (MFE) rather than ARM — its create is a long-running operation that
  can complete with an empty body, and the SDK must re-fetch the created asset instead of crashing.

  This exercises the registry create path for code/data/environment/model assets, regenerated by the
  TypeSpec migration. It is a regression guard for the class of bug where the registry create LRO
  returns ``None`` and an eager deserialize raised ``'NoneType' object has no attribute 'items'``.

Requires a registry (set ``ML_REGISTRY_NAME``); skips gracefully otherwise.

Steps:
  1. Build a registry-scoped MLClient
  2. Create an Environment in the registry; round-trip and assert properties survived
  3. Create a uri_folder Data asset in the registry; round-trip
  4. Create a Model in the registry with tags/properties; round-trip
  5. Clean up (best-effort)
"""

import os

import pytest

from azure.ai.ml import MLClient
from azure.ai.ml.constants import AssetTypes
from azure.ai.ml.entities import Data, Environment, Model


@pytest.fixture(scope="session")
def registry_name():
    name = os.environ.get("ML_REGISTRY_NAME")
    if not name:
        pytest.skip("ML_REGISTRY_NAME not set — registry scenario requires an accessible registry")
    return name


@pytest.fixture(scope="session")
def registry_client(credential, subscription_id, resource_group, registry_name) -> MLClient:
    """A registry-scoped MLClient, just like a customer publishing shared assets."""
    return MLClient(
        credential=credential,
        subscription_id=subscription_id,
        resource_group_name=resource_group,
        registry_name=registry_name,
    )


class TestScenarioRegistryAssetLifecycle:
    """Create environment/data/model assets in a Registry and verify faithful round-trips."""

    @pytest.mark.timeout(900)
    def test_registry_environment_create_round_trip(self, registry_client: MLClient, rand_name):
        """Create an Environment in a registry; the create LRO may return an empty body — must not crash."""
        env_name = rand_name("regenv")
        env = Environment(
            name=env_name,
            version="1",
            image="mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest",
            description="registry-shared environment for scenario test",
            tags={"team": "platform", "shared": "true"},
        )
        created = registry_client.environments.create_or_update(env)
        assert created is not None, "registry environment create returned None (empty-LRO deserialize bug)"
        assert created.name == env_name
        assert created.version == "1"

        fetched = registry_client.environments.get(env_name, "1")
        assert fetched.name == env_name
        assert fetched.tags.get("team") == "platform"
        assert fetched.description == "registry-shared environment for scenario test"

    @pytest.mark.timeout(900)
    def test_registry_data_create_round_trip(self, registry_client: MLClient, rand_name):
        """Create a uri_folder Data asset in a registry and verify round-trip (registry data create path)."""
        data_name = rand_name("regdata")
        data = Data(
            name=data_name,
            version="1",
            type=AssetTypes.URI_FOLDER,
            path="https://azuremlexamples.blob.core.windows.net/datasets/",
            description="registry-shared folder data asset",
            tags={"shared": "true"},
        )
        created = registry_client.data.create_or_update(data)
        assert created is not None, "registry data create returned None (empty-LRO deserialize bug)"
        assert created.name == data_name
        assert created.type == AssetTypes.URI_FOLDER

        fetched = registry_client.data.get(data_name, "1")
        assert fetched.type == AssetTypes.URI_FOLDER
        assert fetched.description == "registry-shared folder data asset"

    @pytest.mark.timeout(900)
    def test_registry_model_create_round_trip(self, registry_client: MLClient, rand_name):
        """Create a Model in a registry with tags/properties and verify round-trip fidelity."""
        model_name = rand_name("regmodel")
        model = Model(
            name=model_name,
            version="1",
            type=AssetTypes.CUSTOM_MODEL,
            path="https://azuremlexamples.blob.core.windows.net/datasets/",
            description="registry-shared model for scenario test",
            tags={"framework": "custom", "shared": "true"},
            properties={"scenario_test": "true"},
        )
        created = registry_client.models.create_or_update(model)
        assert created is not None, "registry model create returned None (empty-LRO deserialize bug)"
        assert created.name == model_name

        fetched = registry_client.models.get(model_name, "1")
        assert fetched.tags.get("framework") == "custom"
        assert fetched.properties.get("scenario_test") == "true"
