# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# ---------------------------------------------------------
"""Scenario: Custom-container inference Environment — inference_config route fidelity + deploy.

Mirrors the customer pattern from:
  https://github.com/Azure/azureml-examples/tree/main/sdk/python/endpoints/online/custom-container
  (online-endpoints-custom-container.ipynb)

Customer story:
  An ML engineer serves a model with a custom web server (e.g. TF Serving) instead of the default
  Flask server. To let Azure ML health-check and route scoring traffic to the container, they declare
  ``inference_config`` on the Environment with three routes — liveness, readiness, and scoring — each
  a ``{port, path}`` pair. If any route is dropped or mis-cased on the wire, the service rejects the
  environment with "You must specify all three of: liveness, readiness and scoring routes".

  This exercises ``Environment.inference_config`` serialization (arm ``InferenceContainerProperties`` /
  ``Route``), regenerated by the TypeSpec migration. It is a regression guard: a customer commonly
  passes ``inference_config`` as a plain dict directly to ``Environment(...)`` (as the sample notebook
  does), which must map to camelCase ``livenessRoute``/``readinessRoute``/``scoringRoute`` on the wire.

Steps:
  1. Create an Environment with an image + inference_config passed as a RAW DICT (as the notebook does)
  2. Round-trip: get the environment and assert all three routes survived with correct port + path
  3. Create a second version passing InferenceContainerProperties/Route MODEL objects; assert identical
  4. Edge case: distinct ports/paths per route to prove no route is silently reused or dropped
  5. Clean up (delete both environment versions' container)
"""

import pytest

from azure.ai.ml import MLClient
from azure.ai.ml.entities import Environment


def _route_port_path(route):
    """Extract (port, path) from a route that may be an arm model or a plain dict."""
    if route is None:
        return None
    if isinstance(route, dict):
        return route.get("port"), route.get("path")
    return getattr(route, "port", None), getattr(route, "path", None)


def _routes(inference_config):
    """Return {name: (port, path)} for the three routes regardless of model-vs-dict shape."""
    assert inference_config is not None, "inference_config was dropped on round-trip"

    def _get(name):
        if isinstance(inference_config, dict):
            return inference_config.get(name)
        return getattr(inference_config, name, None)

    return {
        "liveness": _route_port_path(_get("liveness_route")),
        "readiness": _route_port_path(_get("readiness_route")),
        "scoring": _route_port_path(_get("scoring_route")),
    }


class TestScenarioInferenceEnvironment:
    """Custom-container inference Environment: inference_config route serialization fidelity."""

    @pytest.mark.timeout(600)
    def test_inference_config_raw_dict_round_trip(self, ml_client: MLClient, rand_name):
        """Create an Environment with inference_config as a raw dict (notebook style) and verify routes.

        This is the exact shape the custom-container sample uses. If the three routes are not emitted as
        camelCase ``livenessRoute``/``readinessRoute``/``scoringRoute`` on the wire, the service rejects
        the create — so a successful create + faithful round-trip proves the wire is correct.
        """
        env_name = rand_name("infenv")
        try:
            # ── Step 1: create with a RAW DICT inference_config (exactly like the sample notebook) ──
            env = Environment(
                name=env_name,
                version="1",
                image="docker.io/tensorflow/serving:latest",
                inference_config={
                    "liveness_route": {"port": 8501, "path": "/v1/models/half_plus_two"},
                    "readiness_route": {"port": 8501, "path": "/v1/models/half_plus_two"},
                    "scoring_route": {"port": 8501, "path": "/v1/models/half_plus_two:predict"},
                },
                description="custom-container inference env (raw-dict inference_config)",
            )
            created = ml_client.environments.create_or_update(env)
            assert created.name == env_name
            assert created.version == "1"

            # ── Step 2: round-trip — the three routes must survive with exact port + path ──
            fetched = ml_client.environments.get(env_name, "1")
            routes = _routes(fetched.inference_config)
            assert routes["liveness"] == (8501, "/v1/models/half_plus_two"), routes
            assert routes["readiness"] == (8501, "/v1/models/half_plus_two"), routes
            assert routes["scoring"] == (8501, "/v1/models/half_plus_two:predict"), routes

            # ── Step 4: edge case — distinct ports/paths so a dropped/reused route is caught ──
            env_v2 = Environment(
                name=env_name,
                version="2",
                image="docker.io/tensorflow/serving:latest",
                inference_config={
                    "liveness_route": {"port": 8080, "path": "/health/live"},
                    "readiness_route": {"port": 8081, "path": "/health/ready"},
                    "scoring_route": {"port": 8082, "path": "/score"},
                },
            )
            ml_client.environments.create_or_update(env_v2)
            fetched_v2 = ml_client.environments.get(env_name, "2")
            routes_v2 = _routes(fetched_v2.inference_config)
            assert routes_v2["liveness"] == (8080, "/health/live"), routes_v2
            assert routes_v2["readiness"] == (8081, "/health/ready"), routes_v2
            assert routes_v2["scoring"] == (8082, "/score"), routes_v2
        finally:
            # ── Step 5: cleanup ──
            try:
                ml_client.environments.archive(name=env_name, version="1")
            except Exception as ex:  # pragma: no cover - best-effort cleanup
                print(f"cleanup: could not archive {env_name}:1 — {ex}")
            try:
                ml_client.environments.archive(name=env_name, version="2")
            except Exception as ex:  # pragma: no cover - best-effort cleanup
                print(f"cleanup: could not archive {env_name}:2 — {ex}")

    @pytest.mark.timeout(600)
    def test_inference_config_from_yaml_round_trip(self, ml_client: MLClient, rand_name):
        """An Environment loaded from YAML must round-trip its inference_config routes identically.

        Customers who load an environment from YAML get the schema-produced inference config model (not a
        raw dict). Both construction paths must produce the same accepted wire and the same routes.
        """
        import os
        import tempfile

        from azure.ai.ml import load_environment

        env_name = rand_name("infenvy")
        try:
            with tempfile.TemporaryDirectory() as code_dir:
                yaml_path = os.path.join(code_dir, "env.yml")
                with open(yaml_path, "w", encoding="utf-8") as f:
                    f.write(
                        "$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json\n"
                        f"name: {env_name}\n"
                        "version: '1'\n"
                        "image: docker.io/tensorflow/serving:latest\n"
                        "inference_config:\n"
                        "  liveness_route:\n"
                        "    port: 8501\n"
                        "    path: /v1/models/half_plus_two\n"
                        "  readiness_route:\n"
                        "    port: 8501\n"
                        "    path: /v1/models/half_plus_two\n"
                        "  scoring_route:\n"
                        "    port: 8501\n"
                        "    path: /v1/models/half_plus_two:predict\n"
                    )
                env = load_environment(source=yaml_path)

            ml_client.environments.create_or_update(env)

            fetched = ml_client.environments.get(env_name, "1")
            routes = _routes(fetched.inference_config)
            assert routes["liveness"] == (8501, "/v1/models/half_plus_two"), routes
            assert routes["readiness"] == (8501, "/v1/models/half_plus_two"), routes
            assert routes["scoring"] == (8501, "/v1/models/half_plus_two:predict"), routes
        finally:
            try:
                ml_client.environments.archive(name=env_name, version="1")
            except Exception as ex:  # pragma: no cover - best-effort cleanup
                print(f"cleanup: could not archive {env_name}:1 — {ex}")
